sudo: required
language: node_js
node_js:
 - 12
branches:
 only:
  - master
services:
 - docker
env:
 global:
  - HELM_URL=https://get.helm.sh
  - HELM_TGZ=helm-v3.3.4-linux-amd64.tar.gz
  - DOCKER_REPO=react-template
  - CLUSTER_NAME=test
  - NAMESPACE=react-template
install:
 - wget ${HELM_URL}/${HELM_TGZ}
 - tar xzfv ${HELM_TGZ}
 - PATH=`pwd`/linux-amd64/:$PATH
 - curl -sL https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/linux-installer/idt-installer | bash
jobs:
 include:
  - stage: build and deploy to k8s cluster
    script:
     - ibmcloud login --apikey ${API_KEY} -c <cluster-id> -r eu-de
     - ibmcloud cr region-set eu-central
     - ibmcloud cr login
     - docker build -t ${DOCKER_REPO} .
     - docker push ${DOCKER_REPO}
     - ibmcloud ks cluster config --cluster ${CLUSTER_NAME}
     - kubectl config set-context --current --namespace=${NAMESPACE}
     - helm upgrade --install react-template charts/react-template/
     - kubectl get pods -o custom-columns=POD:.metadata.name --no-headers | grep react-template | xargs kubectl delete pod
